- README.md
Added Johnny's name to read me
> added johnny to read me

- README.md
> David test branch

- README.md
- demo.js
> added luke-name to readme

- README.md
> girish changes

- server/db/models/cart.js
- server/db/models/index.js
- server/db/models/product.js
- server/db/models/user.js
> defined models and associations

- NORMS.md
> added norms

- .travis.yml
- package-lock.json
- package.json
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/productOrder.js
- server/db/models/user.js
> updated models, deployed locally

- script/seed.js
- server/api/users.js
> built user crud apis and seed file

- script/seed.js
- server/db/models/user.js
> added to seed and updated user validations as necessary

- script/seed.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/productOrder.js
> updated seed.  productOrder still not working

- server/api/index.js
- server/api/orders.js
- server/api/productOrders.js
- server/api/products.js
- server/db/models/index.js
> all crud apis built

- script/seed.js
- server/db/models/order.js
> added userId column to orders

- script/seed.js
- server/db/models/user.js
> added CC hashing

- client/store/product.js
- client/store/user.js
- script/seed.js
- server/api/orders.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/productOrder.js
> changed sequelize types, default values

- client/store/user.js
- server/auth/index.js
- server/db/models/user.js
> can now put a user on state through the post login route

- client/app.js
- client/components/AllProducts.js
- client/components/Footer.js
- client/components/user-home.js
> changes to front end

- server/auth/index.js
- server/db/models/user.js
> updated user mode, cleaned up code

- client/store/user.js
> fixed typo in putting singleUser on state

- client/app.js
- client/store/product.js
- client/store/user.js
> 'auth' & 'me' user thunks now working fully 

- client/components/AllProducts.js
- client/components/index.js
- client/components/navbar.js
> AllProducts component now renders correctly in barebones form when the relevant button is clicked

- client/components/AllProducts.js
- client/components/ProductThumbnail.js
- client/components/index.js
- client/store/user.js
> productthumbnail created and incorporated into allproducts + changed some syntax for clarity purposes

- server/api/cart.js
> cart api routes seem to be working

- client/components/Cart.js
- client/store/user.js
- script/seed.js
- server/api/cart.js
- server/db/models/index.js
> view cart is mostly working

- client/components/Cart.js
- client/components/Navbar.js
- client/components/SignIn.js
> cart persists upon refresh

- client/components/Cart.js
- client/components/CartRow.js
- public/style.css
- script/seed.js
> fixing cartrow

- client/components/CartRow.js
> fixed infinite loop issue

- client/components/CartRow.js
- client/store/user.js
- server/api/cart.js
> fixed adding to cart at cart page

- client/components/Cart.js
- client/components/CartRow.js
> fixed empty cart infinite looping using prevProps

- client/components/Account.js
- client/components/SignUp.js
- client/store/user.js
- server/db/models/user.js
> Sign Up works

- client/components/Cart.js
> incomplete users are redirected upon checkout

- client/components/Cart.js
- client/store/user.js
- server/api/cart.js
- server/api/users.js
> fixed cart infinite loop in a very ugly way

- client/store/user.js
- server/api/cart.js
- server/auth/index.js
> fixed password alert logic

- client/components/Account.js
- client/components/AccountUpdateForm.js
- client/components/NavBar2.js
- client/components/SignIn.js
> fixed some of the user update components

- client/store/user.js
> update user works

- client/components/NavBar2.js
> made a critical change in navbar2
